receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318  

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
    sending_queue:
      enabled: true
      queue_size: 1000
      num_consumers: 10
  prometheus:
    endpoint: 0.0.0.0:9090
  debug:
    verbosity: detailed

processors:
extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus, debug]
