[auth]
# some feature (like dashboards) require login even if anonymous access is enabled
anonymous_enabled = false
disable_login_form = false

[security]
admin_user = admin
admin_password = admin

[feature_toggles]
enable = metricsSummaryAndDrillDown traceqlEditor
